Import('flags')
Import('env')
Import('prefix')

libname = "".join(['-l', prefix, 'study'])
progname = "".join(["#", prefix, "runtests"])

test_sources = Glob("*_test.cpp") + Glob("lessons/*.cpp") + ["test_main.cpp"]

test_env = env.Clone()
test_env.MergeFlags([flags['test'], libname])
test_env.Program(progname, test_sources)

