Import('env')
Import('prefix')

frame_sources = Glob("*.cpp")

target = "".join(['#lib/', prefix, 'study'])

env.StaticLibrary(target, frame_sources)

exports = {
	'env': env,
	'prefix': prefix,
}

SConscript('test/SConscript', exports=exports)

